In [12]:
import pandas as pd
denver_parent_data = pd.read_csv("../datasets/denver-data.csv")

In [13]:
denver_address = pd.read_csv("./denver-address.csv")
denver_crime = pd.read_csv("./denver-crime.csv")
denver_date = pd.read_csv("../merged-datasets/merged-dates.csv")

In [14]:
#Adding Denver crime-key
denver_parent_data = pd.concat([denver_parent_data, denver_crime], axis=1)
denver_parent_data.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,...,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC,crime_key,crime_type,crime_report_time,crime_start_time,crime_end_time
0,2.016377e+09,2.016380e+15,5213,0,weapon-unlawful-discharge-of,all-other-crimes,6/15/2016 11:31:00 PM,NaN,6/15/2016 11:31:00 PM,NaN,...,5,521,montbello,1,0,eea886bf-a231-425b-ad4c-769c101d4d82,Other Crimes,23:31:00,23:31:00,NaN
1,2.018600e+10,2.018600e+16,2399,0,theft-other,larceny,10/11/2017 12:30:00 PM,10/11/2017 4:55:00 PM,1/29/2018 5:53:00 PM,NaN,...,5,522,gateway-green-valley-ranch,1,0,7953ed57-16be-4527-9ca2-d8438cdb0a23,Theft,17:53:00,12:30:00,16:55:00
2,2.016600e+10,2.016600e+16,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,3/4/2016 8:00:00 PM,4/25/2016 8:00:00 AM,4/26/2016 9:02:00 PM,2932 S JOSEPHINE ST,...,3,314,wellshire,1,0,a653f1ea-2c0c-4246-bc53-97db8031e9aa,Theft from Vehicle,21:02:00,20:00:00,08:00:00
3,2.018723e+08,2.018720e+14,2399,0,theft-other,larceny,1/30/2018 7:20:00 PM,NaN,1/30/2018 10:29:00 PM,705 S COLORADO BLVD,...,3,312,belcaro,1,0,22c71dbe-b6e8-4f40-8b44-21524725b093,Theft,22:29:00,19:20:00,NaN
4,2.017411e+09,2.017410e+15,2303,0,theft-shoplift,larceny,6/22/2017 8:53:00 PM,NaN,6/23/2017 4:09:00 PM,2810 E 1ST AVE,...,3,311,cherry-creek,1,0,c3b31f97-e639-4d21-b95c-1d6e4cfc60d7,Theft,16:09:00,20:53:00,NaN

In [15]:
#only picking colummns that are needed
denver_parent_data = denver_parent_data[['crime_key', 'INCIDENT_ADDRESS', 'FIRST_OCCURRENCE_DATE', 'IS_TRAFFIC', 'crime_report_time', 'crime_type', 'crime_start_time']]

In [16]:
#Adding Denver address-key
denver_parent_data = pd.merge(denver_parent_data, denver_address, how='left', left_on=['INCIDENT_ADDRESS'], right_on = ['location_name'])

In [17]:
denver_parent_data.head()

,crime_key,INCIDENT_ADDRESS,FIRST_OCCURRENCE_DATE,IS_TRAFFIC,crime_report_time,crime_type,crime_start_time,location_key,location_name,neighborhood,city,longitude,latitude
0,eea886bf-a231-425b-ad4c-769c101d4d82,NaN,6/15/2016 11:31:00 PM,0,23:31:00,Other Crimes,23:31:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,NaN,montbello,Denver,-104.809881,39.773188
1,7953ed57-16be-4527-9ca2-d8438cdb0a23,NaN,10/11/2017 12:30:00 PM,0,17:53:00,Theft,12:30:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,NaN,montbello,Denver,-104.809881,39.773188
2,a653f1ea-2c0c-4246-bc53-97db8031e9aa,2932 S JOSEPHINE ST,3/4/2016 8:00:00 PM,0,21:02:00,Theft from Vehicle,20:00:00,beb00ff6-50f9-47d4-b6ce-fccced9416df,2932 S JOSEPHINE ST,wellshire,Denver,-104.957381,39.663490
3,22c71dbe-b6e8-4f40-8b44-21524725b093,705 S COLORADO BLVD,1/30/2018 7:20:00 PM,0,22:29:00,Theft,19:20:00,94bb4127-7768-4ac9-bac2-9bf22d883ea4,705 S COLORADO BLVD,belcaro,Denver,-104.941440,39.702698
4,c3b31f97-e639-4d21-b95c-1d6e4cfc60d7,2810 E 1ST AVE,6/22/2017 8:53:00 PM,0,16:09:00,Theft,20:53:00,63c820a1-a440-47ba-a3b9-c6005182d47a,2810 E 1ST AVE,cherry-creek,Denver,-104.955370,39.717107

In [18]:
denver_parent_data.drop(columns=['location_name', 'neighborhood', 'city'], inplace=True)
denver_parent_data.head()

,crime_key,INCIDENT_ADDRESS,FIRST_OCCURRENCE_DATE,IS_TRAFFIC,crime_report_time,crime_type,crime_start_time,location_key,longitude,latitude
0,eea886bf-a231-425b-ad4c-769c101d4d82,NaN,6/15/2016 11:31:00 PM,0,23:31:00,Other Crimes,23:31:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188
1,7953ed57-16be-4527-9ca2-d8438cdb0a23,NaN,10/11/2017 12:30:00 PM,0,17:53:00,Theft,12:30:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188
2,a653f1ea-2c0c-4246-bc53-97db8031e9aa,2932 S JOSEPHINE ST,3/4/2016 8:00:00 PM,0,21:02:00,Theft from Vehicle,20:00:00,beb00ff6-50f9-47d4-b6ce-fccced9416df,-104.957381,39.663490
3,22c71dbe-b6e8-4f40-8b44-21524725b093,705 S COLORADO BLVD,1/30/2018 7:20:00 PM,0,22:29:00,Theft,19:20:00,94bb4127-7768-4ac9-bac2-9bf22d883ea4,-104.941440,39.702698
4,c3b31f97-e639-4d21-b95c-1d6e4cfc60d7,2810 E 1ST AVE,6/22/2017 8:53:00 PM,0,16:09:00,Theft,20:53:00,63c820a1-a440-47ba-a3b9-c6005182d47a,-104.955370,39.717107

In [19]:
date_values = denver_parent_data['FIRST_OCCURRENCE_DATE'].values

year = []
month = []
day = []
completeDay = []

for date in date_values:
    date = date.split() # Split on whitespace
    date = date[0] # Grab first portion which m/d/y
    completeDay.append(date)# Store the complete day to remove duplicates later
    date = date.split('/') # Split into m, d and y and turn into int
    month.append(int(date[0]))
    day.append(int(date[1]))
    year.append(int(date[2]))

denver_parent_data['year'] = year
denver_parent_data['month'] = month
denver_parent_data['day'] = day
denver_parent_data.head()

,crime_key,INCIDENT_ADDRESS,FIRST_OCCURRENCE_DATE,IS_TRAFFIC,crime_report_time,crime_type,crime_start_time,location_key,longitude,latitude,year,month,day
0,eea886bf-a231-425b-ad4c-769c101d4d82,NaN,6/15/2016 11:31:00 PM,0,23:31:00,Other Crimes,23:31:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188,2016,6,15
1,7953ed57-16be-4527-9ca2-d8438cdb0a23,NaN,10/11/2017 12:30:00 PM,0,17:53:00,Theft,12:30:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188,2017,10,11
2,a653f1ea-2c0c-4246-bc53-97db8031e9aa,2932 S JOSEPHINE ST,3/4/2016 8:00:00 PM,0,21:02:00,Theft from Vehicle,20:00:00,beb00ff6-50f9-47d4-b6ce-fccced9416df,-104.957381,39.663490,2016,3,4
3,22c71dbe-b6e8-4f40-8b44-21524725b093,705 S COLORADO BLVD,1/30/2018 7:20:00 PM,0,22:29:00,Theft,19:20:00,94bb4127-7768-4ac9-bac2-9bf22d883ea4,-104.941440,39.702698,2018,1,30
4,c3b31f97-e639-4d21-b95c-1d6e4cfc60d7,2810 E 1ST AVE,6/22/2017 8:53:00 PM,0,16:09:00,Theft,20:53:00,63c820a1-a440-47ba-a3b9-c6005182d47a,-104.955370,39.717107,2017,6,22

In [20]:
#Add Date Key
denver_parent_data = pd.merge(denver_parent_data, denver_date, how='left', left_on=['year', 'month', 'day'], right_on = ['year', 'month', 'day'])

In [21]:
denver_parent_data.head()

,crime_key,INCIDENT_ADDRESS,FIRST_OCCURRENCE_DATE,IS_TRAFFIC,crime_report_time,crime_type,crime_start_time,location_key,longitude,latitude,year,month,day,date_key,day_of_week,is_weekend,is_american_holiday,american_holiday_name,is_canadian_holiday,canadian_holiday_name
0,eea886bf-a231-425b-ad4c-769c101d4d82,NaN,6/15/2016 11:31:00 PM,0,23:31:00,Other Crimes,23:31:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188,2016,6,15,dd30cdbb-dd8a-4dc6-80e3-ba07407a4ff7,Wednesday,False,False,NaN,False,NaN
1,7953ed57-16be-4527-9ca2-d8438cdb0a23,NaN,10/11/2017 12:30:00 PM,0,17:53:00,Theft,12:30:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188,2017,10,11,30cfd6cd-2f56-4da2-920e-09cc958fe766,Wednesday,False,False,NaN,False,NaN
2,a653f1ea-2c0c-4246-bc53-97db8031e9aa,2932 S JOSEPHINE ST,3/4/2016 8:00:00 PM,0,21:02:00,Theft from Vehicle,20:00:00,beb00ff6-50f9-47d4-b6ce-fccced9416df,-104.957381,39.663490,2016,3,4,c4f2a260-7bc4-4ba4-8961-240e13db85ae,Friday,False,False,NaN,False,NaN
3,22c71dbe-b6e8-4f40-8b44-21524725b093,705 S COLORADO BLVD,1/30/2018 7:20:00 PM,0,22:29:00,Theft,19:20:00,94bb4127-7768-4ac9-bac2-9bf22d883ea4,-104.941440,39.702698,2018,1,30,10e79260-6164-4ac2-94c9-8dba650b1abd,Tuesday,False,False,NaN,False,NaN
4,c3b31f97-e639-4d21-b95c-1d6e4cfc60d7,2810 E 1ST AVE,6/22/2017 8:53:00 PM,0,16:09:00,Theft,20:53:00,63c820a1-a440-47ba-a3b9-c6005182d47a,-104.955370,39.717107,2017,6,22,c0a01024-1be7-4763-ad42-a6bd4737268f,Thursday,False,False,NaN,False,NaN

In [22]:
denver_parent_data = denver_parent_data.iloc[:, 0:15]
denver_parent_data.head()

,crime_key,INCIDENT_ADDRESS,FIRST_OCCURRENCE_DATE,IS_TRAFFIC,crime_report_time,crime_type,crime_start_time,location_key,longitude,latitude,year,month,day,date_key,day_of_week
0,eea886bf-a231-425b-ad4c-769c101d4d82,NaN,6/15/2016 11:31:00 PM,0,23:31:00,Other Crimes,23:31:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188,2016,6,15,dd30cdbb-dd8a-4dc6-80e3-ba07407a4ff7,Wednesday
1,7953ed57-16be-4527-9ca2-d8438cdb0a23,NaN,10/11/2017 12:30:00 PM,0,17:53:00,Theft,12:30:00,dcd36c09-2095-4935-bac2-62bb9ba8738e,-104.809881,39.773188,2017,10,11,30cfd6cd-2f56-4da2-920e-09cc958fe766,Wednesday
2,a653f1ea-2c0c-4246-bc53-97db8031e9aa,2932 S JOSEPHINE ST,3/4/2016 8:00:00 PM,0,21:02:00,Theft from Vehicle,20:00:00,beb00ff6-50f9-47d4-b6ce-fccced9416df,-104.957381,39.663490,2016,3,4,c4f2a260-7bc4-4ba4-8961-240e13db85ae,Friday
3,22c71dbe-b6e8-4f40-8b44-21524725b093,705 S COLORADO BLVD,1/30/2018 7:20:00 PM,0,22:29:00,Theft,19:20:00,94bb4127-7768-4ac9-bac2-9bf22d883ea4,-104.941440,39.702698,2018,1,30,10e79260-6164-4ac2-94c9-8dba650b1abd,Tuesday
4,c3b31f97-e639-4d21-b95c-1d6e4cfc60d7,2810 E 1ST AVE,6/22/2017 8:53:00 PM,0,16:09:00,Theft,20:53:00,63c820a1-a440-47ba-a3b9-c6005182d47a,-104.955370,39.717107,2017,6,22,c0a01024-1be7-4763-ad42-a6bd4737268f,Thursday

In [ ]:
def dist_bn_two_points(add1, add2):
    R = 6373.0


    lat1 = math.radians(52.2296756)

    lon1 = math.radians(21.0122287)
    lat2 = math.radians(52.406374)
    lon2 = math.radians(16.9251681)

    dlon = lon2 - lon1

    dlat = lat2 - lat1
    
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    distance = R * c
    
    return distance