In [1]:
import pandas as pd # DataFrame, Series
import numpy as np # Scienitific computing packages - Array

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import export_graphviz

from matplotlib import pyplot as plt
import seaborn as sns

import graphviz
import pydotplus
import io
from scipy import misc

In [2]:
data = pd.read_csv('./classification_dataset.csv')

In [3]:
data.head()

,Neighborhood,Is_Traffic,Is_fatal,Is_nighttime,Crime_type,Is_american_holiday,Is_canadian_holiday,Month,City,Season
0,montbello,False,False,True,Theft,False,False,10,Denver,Fall
1,northeast-park-hill,True,False,True,Traffic Accident,False,False,1,Denver,Winter
2,montbello,True,False,True,Traffic Accident,False,False,1,Denver,Winter
3,montbello,False,False,True,Offence Against a Person,False,False,1,Denver,Winter
4,lincoln-park,False,False,True,Theft of Vehicle,False,False,1,Denver,Winter

In [4]:
le = LabelEncoder()
le.fit(data['Season'])
data['Season'] = le.transform(data['Season'])

In [5]:
data.head()

,Neighborhood,Is_Traffic,Is_fatal,Is_nighttime,Crime_type,Is_american_holiday,Is_canadian_holiday,Month,City,Season
0,montbello,False,False,True,Theft,False,False,10,Denver,0
1,northeast-park-hill,True,False,True,Traffic Accident,False,False,1,Denver,3
2,montbello,True,False,True,Traffic Accident,False,False,1,Denver,3
3,montbello,False,False,True,Offence Against a Person,False,False,1,Denver,3
4,lincoln-park,False,False,True,Theft of Vehicle,False,False,1,Denver,3

In [6]:
data = pd.get_dummies(data)

In [7]:
data.head()

,Is_Traffic,Is_fatal,Is_nighttime,Is_american_holiday,Is_canadian_holiday,Month,Season,Neighborhood_Arbutus Ridge,Neighborhood_Central Business District,Neighborhood_Dunbar-Southlands,...,Crime_type_Mischief,Crime_type_Offence Against a Person,Crime_type_Other Crimes,Crime_type_Other Crimes,Crime_type_Theft,Crime_type_Theft from Vehicle,Crime_type_Theft of Vehicle,Crime_type_Traffic Accident,City_Denver,City_Vancouver
0,False,False,True,False,False,10,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,True,False,True,False,False,1,3,0,0,0,...,0,0,0,0,0,0,0,1,1,0
2,True,False,True,False,False,1,3,0,0,0,...,0,0,0,0,0,0,0,1,1,0
3,False,False,True,False,False,1,3,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,False,False,True,False,False,1,3,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [8]:
list(data.columns.values)

['Is_Traffic',
 'Is_fatal',
 'Is_nighttime',
 'Is_american_holiday',
 'Is_canadian_holiday',
 'Month',
 'Season',
 'Neighborhood_Arbutus Ridge',
 'Neighborhood_Central Business District',
 'Neighborhood_Dunbar-Southlands',
 'Neighborhood_Fairview',
 'Neighborhood_Grandview-Woodland',
 'Neighborhood_Hastings-Sunrise',
 'Neighborhood_Kensington-Cedar Cottage',
 'Neighborhood_Kerrisdale',
 'Neighborhood_Killarney',
 'Neighborhood_Kitsilano',
 'Neighborhood_Marpole',
 'Neighborhood_Mount Pleasant',
 'Neighborhood_Musqueam',
 'Neighborhood_Oakridge',
 'Neighborhood_Renfrew-Collingwood',
 'Neighborhood_Riley Park',
 'Neighborhood_Shaughnessy',
 'Neighborhood_South Cambie',
 'Neighborhood_Stanley Park',
 'Neighborhood_Strathcona',
 'Neighborhood_Sunset',
 'Neighborhood_Victoria-Fraserview',
 'Neighborhood_West End',
 'Neighborhood_West Point Grey',
 'Neighborhood_athmar-park',
 'Neighborhood_auraria',
 'Neighborhood_baker',
 'Neighborhood_barnum',
 'Neighborhood_barnum-west',
 'Neighborhood_bear-valley',
 'Neighborhood_belcaro',
 'Neighborhood_berkeley',
 'Neighborhood_capitol-hill',
 'Neighborhood_cbd',
 'Neighborhood_chaffee-park',
 'Neighborhood_cheesman-park',
 'Neighborhood_cherry-creek',
 'Neighborhood_city-park',
 'Neighborhood_city-park-west',
 'Neighborhood_civic-center',
 'Neighborhood_clayton',
 'Neighborhood_cole',
 'Neighborhood_college-view-south-platte',
 'Neighborhood_congress-park',
 'Neighborhood_cory-merrill',
 'Neighborhood_country-club',
 'Neighborhood_dia',
 'Neighborhood_east-colfax',
 'Neighborhood_elyria-swansea',
 'Neighborhood_five-points',
 'Neighborhood_fort-logan',
 'Neighborhood_gateway-green-valley-ranch',
 'Neighborhood_globeville',
 'Neighborhood_goldsmith',
 'Neighborhood_hale',
 'Neighborhood_hampden',
 'Neighborhood_hampden-south',
 'Neighborhood_harvey-park',
 'Neighborhood_harvey-park-south',
 'Neighborhood_highland',
 'Neighborhood_hilltop',
 'Neighborhood_indian-creek',
 'Neighborhood_jefferson-park',
 'Neighborhood_kennedy',
 'Neighborhood_lincoln-park',
 'Neighborhood_lowry-field',
 'Neighborhood_mar-lee',
 'Neighborhood_marston',
 'Neighborhood_montbello',
 'Neighborhood_montclair',
 'Neighborhood_north-capitol-hill',
 'Neighborhood_north-park-hill',
 'Neighborhood_northeast-park-hill',
 'Neighborhood_overland',
 'Neighborhood_platt-park',
 'Neighborhood_regis',
 'Neighborhood_rosedale',
 'Neighborhood_ruby-hill',
 'Neighborhood_skyland',
 'Neighborhood_sloan-lake',
 'Neighborhood_south-park-hill',
 'Neighborhood_southmoor-park',
 'Neighborhood_speer',
 'Neighborhood_stapleton',
 'Neighborhood_sun-valley',
 'Neighborhood_sunnyside',
 'Neighborhood_union-station',
 'Neighborhood_university',
 'Neighborhood_university-hills',
 'Neighborhood_university-park',
 'Neighborhood_valverde',
 'Neighborhood_villa-park',
 'Neighborhood_virginia-village',
 'Neighborhood_washington-park',
 'Neighborhood_washington-park-west',
 'Neighborhood_washington-virginia-vale',
 'Neighborhood_wellshire',
 'Neighborhood_west-colfax',
 'Neighborhood_west-highland',
 'Neighborhood_westwood',
 'Neighborhood_whittier',
 'Neighborhood_windsor',
 'Crime_type_Burglary',
 'Crime_type_Homicide',
 'Crime_type_Mischief',
 'Crime_type_Offence Against a Person',
 'Crime_type_Other  Crimes',
 'Crime_type_Other Crimes',
 'Crime_type_Theft',
 'Crime_type_Theft from Vehicle',
 'Crime_type_Theft of Vehicle',
 'Crime_type_Traffic Accident',
 'City_Denver',
 'City_Vancouver']

In [9]:
train, test = train_test_split(data, test_size = 0.3)

In [10]:
c = DecisionTreeClassifier(min_samples_split = 100)

In [11]:
features = list(data.columns.values)

In [12]:
x_train = train[features]
y_train = train["Month"]

x_test = test[features]
y_text = test["Month"]

In [13]:
dt = c.fit(x_train, y_train)

In [14]:
def show_tree(tree, features, path):
    f = io.StringIO()
    export_graphviz(tree, out_file=f, feature_names=features)
    pydotplus.graph_from_dot_data(f.getvalue()).write_png(path)
    img = misc.imread(path)
    plt.rcParams["figure.figsize"] = (20,20)
    plt.imshow(img)

In [16]:
dt.score(x_train, y_train)

1.0

In [17]:
test_row = data.loc[1]

In [32]:
s = data.loc[(data["Season"] == 2) & (data["Crime_type_Theft"] == 1) & (data["City_Vancouver"] == 1)]

In [24]:
data.loc[]

array([True, False, True, False, False, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=object)

In [20]:
data.head()

,Is_Traffic,Is_fatal,Is_nighttime,Is_american_holiday,Is_canadian_holiday,Month,Season,Neighborhood_Arbutus Ridge,Neighborhood_Central Business District,Neighborhood_Dunbar-Southlands,...,Crime_type_Mischief,Crime_type_Offence Against a Person,Crime_type_Other Crimes,Crime_type_Other Crimes,Crime_type_Theft,Crime_type_Theft from Vehicle,Crime_type_Theft of Vehicle,Crime_type_Traffic Accident,City_Denver,City_Vancouver
0,False,False,True,False,False,10,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,True,False,True,False,False,1,3,0,0,0,...,0,0,0,0,0,0,0,1,1,0
2,True,False,True,False,False,1,3,0,0,0,...,0,0,0,0,0,0,0,1,1,0
3,False,False,True,False,False,1,3,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,False,False,True,False,False,1,3,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [34]:
dt.predict(s)

array([8, 8, 7, ..., 7, 7, 7], dtype=int64)

In [33]:
s

,Is_Traffic,Is_fatal,Is_nighttime,Is_american_holiday,Is_canadian_holiday,Month,Season,Neighborhood_Arbutus Ridge,Neighborhood_Central Business District,Neighborhood_Dunbar-Southlands,...,Crime_type_Mischief,Crime_type_Offence Against a Person,Crime_type_Other Crimes,Crime_type_Other Crimes,Crime_type_Theft,Crime_type_Theft from Vehicle,Crime_type_Theft of Vehicle,Crime_type_Traffic Accident,City_Denver,City_Vancouver
6367,False,False,False,False,False,8,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
6372,False,False,False,False,False,8,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
6373,False,False,False,False,False,7,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
6375,False,False,False,False,False,6,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
6379,False,False,True,False,False,7,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660638,False,False,False,False,True,7,2,0,1,0,...,0,0,0,0,1,0,0,0,0,1
660639,False,False,False,False,False,6,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
660641,False,False,True,False,False,7,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
660643,False,False,False,False,True,7,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
660644,False,False,True,False,False,7,2,0,0,0,...,0,0,0,0,1,0,0,0,0,1